title: Bryan Summersett
email: bsummersett@gmail.com
description: > # this means to ignore newlines until the next entry
  Bryan Summersett's home page.
url: "https://bsumm.net" # the base hostname & protocol for your site
twitter_username: bryansum
github_username:  bryansum

# Layout
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: default

# Build settings
markdown: kramdown
