#!/usr/bin/env ruby
# Based on a script by Alex Payne: https://gist.github.com/106869/15b2e64325ee26f2404679eb54d77f59f26c1994

ROOT_DIR = File.join(File.dirname(__FILE__), '/..')

title = ARGV[0]

unless title
  puts %{Usage: #{$0} "the-post-title"}
  exit(-1)
end

datetime = (Time.now).strftime('%Y-%m-%d')

# E.g. 2006-07-16_11-41-batch-open-urls-from-clipboard.md
slug = title.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
path = "#{ROOT_DIR}/_posts/#{datetime}-#{slug}.md"

header = <<-END
---
title: #{title}
layout: post
---

END

File.open(path, 'w') {|f| f << header }

puts "Your post can be found at: #{path}"

